inferenceservice:
  name: granite3.2-8b
runtime:
  name: runtime-granite32-8b

description: Deploy a model to a OpenShift cluster using Helm.
version: latest
image_repository: quay.io
image_namespace: rhoai-mlops
autoscaling: false
canary: {}
  # trafficPercent: 10