apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: {{ .Values.inferenceservice.name }}
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: {{ .Values.inferenceservice.name }}
  finalizers:
    - inferenceservice.finalizers
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 16Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: '1'
      runtime: {{ .Values.runtime.name }}
      storage:
        key: {{ .Values.inferenceservice.storage.key }}
        name: {{ .Values.inferenceservice.storage.name }}
    containerConcurrency: 1
    tolerations:
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "True"
      effect: "NoSchedule"